### PR TITLE
🐛 FIX: front-matter: `IndexError` if first line is single dash

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
cc @choldgraf

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
Can you add a test fixture for this thanks

**Comment by choldgraf** [comment]
@chrisjsewell would that be here: https://raw.githubusercontent.com/executablebooks/mdit-py-plugins/master/tests/fixtures/myst_block.md ?

**Comment by chrisjsewell** [comment]
no here: https://raw.githubusercontent.com/executablebooks/mdit-py-plugins/master/tests/fixtures/front_matter.md

**Comment by jpmckinney** [comment]
@chrisjsewell I've added a simple test.

**Comment by chrisjsewell** [comment]
exception:

```python
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/mdit_py_plugins/front_matter/index.py", line 51, in frontMatter
    if marker_str[(pos - start) % marker_len] != state.src[pos]:
IndexError: string index out of range
```

**Pull request merged**
