### PR TITLE
🔧 MAINTAIN: Fix tests if `Token.attrs` is of type `List[tuple]]`

### PR DESCRIPTION
**Pull request by hukkinj1**
This PR will fix tests if https://github.com/executablebooks/markdown-it-py/pull/102 is merged to `markdown-it-py`. `mdit-py-plugins` does not mutate `Token.attrs` items though so even though test assertions break, no functional code should break if https://github.com/executablebooks/markdown-it-py/pull/102 is merged

### CODE REVIEW

**Comment by chrisjsewell** [comment]
superseded by #13

**Comment by hukkinj1** [comment]
@chrisjsewell I believe we still need the test assertion fixes in this PR, in case https://github.com/executablebooks/markdown-it-py/pull/102 is merged.

**Comment by chrisjsewell** [comment]
Bet we don't 😉

**Comment by hukkinj1** [comment]
Haha, lets see I'm not 100% sure either. But surely that makes the upstream `attrSet` set tuples instead. What I'm not sure then is how the pytest `assert`s deal with that.

**Pull request closed without merging**
